name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    environment:
      name: AWS_DEPLOYMENT

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Disable Terraform Debug
        run: |
          echo "TF_LOG=ERROR" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Check Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Set Terraform Variables
        run: |
          touch terraform.tfvars
          echo "webapp_ami_id = \"${{ vars.WEBAPP_AMI_ID }}\"" >> terraform.tfvars
          echo "mysql_ami_id = \"${{ vars.MYSQL_AMI_ID }}\"" >> terraform.tfvars
          echo "database_username = \"${{ vars.DATABASE_USERNAME }}\"" >> terraform.tfvars
          echo "database_password = \"${{ secrets.DATABASE_PASSWORD }}\"" >> terraform.tfvars
          echo "webapp_secret_key = \"${{ secrets.WEBAPP_SECRET_KEY }}\"" >> terraform.tfvars

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: |
          echo "WEBAPP_IP=$(terraform output -raw webapp_public_ip)" >> $GITHUB_ENV

      - name: Create `tests/.env` File
        run: |
          echo "HOST=${{ env.WEBAPP_IP }}" > tests/.env
          echo "Current HOST: ${{ env.WEBAPP_IP }}"

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Active Python Environment
        working-directory: tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: tests
        run: |
          source .venv/bin/activate
          pytest --disable-warnings -v

      - name: Terraform Destroy
        if: always()
        continue-on-error: true
        run: terraform destroy -auto-approve
